spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/jx_etl?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
      username: root
      password: rootroot
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      #Oracle需要打开注释
      #validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        #login-username: admin
        #login-password: admin
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: false
        wall:
          config:
            multi-statement-allow: true

# 注册中心配置
eureka:
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    non-secure-port: ${server.port}
  client:
    service-url:
      defaultZone: http://123.207.126.81:8761/eureka/

seaboxdata:
  auth:
    hostname:

#统一认证
auth:
  login:
    url: http://123.207.126.81:30002/login/toLogin?redirect_url=http%3A%2F%2Flocalhost%3A7202%2Fjx-etl%2Floginback

system-params:
#  配置日志下载目录 /home/etl/ETLAuto/LOG/
  file_download_dir: d:/udf/LOG/
#  配置公共脚本上传目录 /home/etl/ETLAuto/app/ d:/home/etl/ETLAuto/app/
  public_script_upload_dir: d:/udf/app/
#  配置作业脚本上传目录
  hql_script_upload_dir: /udf/APP/
# 配置作业控制文件路径
  control_file_dir: /home/etl/ETLAuto/DATA/receive/
# 执行脚本软链接目录
  exec_file_ln_dir: /udf/APP/
# 是否创建软连接标志
  create_ln_flag: false
# 作业配置导出文件
  config_export_dir: d:/udf/tmp/
# cas登录服务地址
#  cas_url: https://127.0.0.1:8443/cas/login?locale=zh_CN&service=http%3A%2F%2F127.0.0.1%3A7202%2Fjx-etl%2Findex.html
  cas_url: http://172.26.64.109:7001/GovSSOService/SSOSecService?LinkType=online&LinkID=gydsj_sjpcl&sid=871b412eab6ea3e7b21cb2dfa4b64c58
  portal_url: http://172.26.64.109:7001/GovSSOService/SSOSecService?LinkType=online&LinkID=gydsj_sjpcl&sid=871b412eab6ea3e7b21cb2dfa4b64c58
  portal_app: 批量数据处理
  soap_url: http://127.0.0.1:18001/portal/intlDataSynchronizedService?wsdl
  cas_server_url_prefix: https://127.0.0.1:8443/cas
  project_url: http://localhost:7202/
  top_menu_url: http://172.26.60.219:8081/app/api_v1/getMenuUrlsByCaId

