# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 9095
  servlet:
    context-path: /jx-etl

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    druid:
      first:  #数据源1
        url: jdbc:mysql://192.166.162.150:3506/etldb?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
        username: etl
        password: etl123
      second:  #数据源2
        url: jdbc:mysql://192.166.162.150:3506/etldb?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
        username: etl
        password: etl123
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      #validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        #login-username: admin
        #login-password: admin
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: false
        wall:
          config:
            multi-statement-allow: true

system-params:
  #  配置日志下载目录
  file_download_dir: /usr/share/etl/LOG/
  #  配置公共脚本上传目录
  public_script_upload_dir: /usr/share/etl/app/
  #  配置作业脚本上传目录
  hql_script_upload_dir: /usr/share/etl/app/
  # 配置作业控制文件路径
  control_file_dir: /usr/share/etl/DATA/receive/
  # 执行脚本软链接目录
  exec_file_ln_dir: /usr/share/etl/APP/
  # 是否创建软连接标志
  create_ln_flag: true
  # 作业配置导出文件
  config_export_dir: /usr/share/etl/tmp/
  # cas登录服务地址
  cas_url: http://172.26.64.109:7001/GovSSOService/SSOSecService?LinkType=online&LinkID=gydsj_sjpcl&sid=871b412eab6ea3e7b21cb2dfa4b64c58
  portal_url: http://172.26.64.109:7001/GovSSOService/SSOSecService?LinkType=online&LinkID=gydsj_sjpcl&sid=871b412eab6ea3e7b21cb2dfa4b64c58
  portal_app: 批量数据处理系统
  soap_url: http://172.26.52.167:18001/portal/intlDataSynchronizedService?wsdl
  cas_server_url_prefix: http://172.26.52.167:17001/cas
  project_url: http://172.26.52.168:9095/jx-etl/