spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://10.217.17.115:3306/etldb?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
      username: etl
      password: edw123
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      #Oracle需要打开注释
      #validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        #login-username: admin
        #login-password: admin
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: false
        wall:
          config:
            multi-statement-allow: true

auth-server-url: http://172.25.13.75:31234

# spring security 配置
security:
  oauth2:
    client:
      client-id: testclientid
      client-secret: 123456
      scope: read_userinfo
      access-token-uri: ${auth-server-url}/oauth/token
      user-authorization-uri: ${auth-server-url}/oauth/authorize
    resource:
      loadBalanced: true
      token-info-uri: ${auth-server-url}/oauth/check_token
      check-token: ${auth-server-url}/oauth/check_token

seaboxdata:
  auth:
    hostname:

#统一认证
auth:
  config:
    need: true
  login:
    url: http://auth-frontier.jxwda.bjdx.gov.cn/frontier/auth/toLogin?redirect_url=http%3A%2F%2F10.217.17.115%3A7202%2Fjx-etl%2Floginback


system-params:
  #  配置日志下载目录
  file_download_dir: /usr/share/etl/LOG/
  #  配置公共脚本上传目录
  public_script_upload_dir: /usr/share/etl/app/
  #  配置作业脚本上传目录
  hql_script_upload_dir: /usr/share/etl/app/
  # 配置作业控制文件路径
  control_file_dir: /usr/share/etl/DATA/receive/
  # 执行脚本软链接目录
  exec_file_ln_dir: /usr/share/etl/APP/
  # 是否创建软连接标志
  create_ln_flag: true
  # 作业配置导出文件
  config_export_dir: /home/etl/tmp/
  # cas登录服务地址
  cas-service-url: http://10.217.17.116:8094/cas
  project-url: http://10.217.17.115:7202/jx-etl/
  portal-app: 备案项目管理
  soap_url: http://10.217.17.116:18001/portal/intlDataSynchronizedService?wsdl
