spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://10.192.72.92:3306/etldb?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
      username: etl
      password: edw123
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      #Oracle需要打开注释
      #validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        #login-username: admin
        #login-password: admin
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: false
        wall:
          config:
            multi-statement-allow: true

auth-url: http://10.192.72.82:31003
auth-frontier-url: http://10.192.72.82:31000

#统一认证
auth:
  client:
    id: testclientid
    secret: 123456
  config:
    need: true
  login:
    url: ${auth-url}/bj/cas/authDoLogin?redirect=http%3A%2F%2F{{etl_ip}}%3A{{etl_port}}%2Fjx-etl%2Floginback
  logout:
    url: http://10.217.17.116:8094/cas/logout

etl-root-url: /usr/share/etl

system-params:
  #  配置日志下载目录
  file_download_dir: ${etl-root-url}/LOG/
  #  配置公共脚本上传目录
  public_script_upload_dir: ${etl-root-url}/app/
  #  配置作业脚本上传目录
  hql_script_upload_dir: ${etl-root-url}/app/
  # 配置作业控制文件路径
  control_file_dir: ${etl-root-url}/DATA/receive/
  # 执行脚本软链接目录
  exec_file_ln_dir: ${etl-root-url}/APP/
  # 是否创建软连接标志
  create_ln_flag: true
  # 作业配置导出文件
  config_export_dir: ${etl-root-url}/tmp/
